export const GET_CHOOSE_ALBUM = 'GET_CHOOSE_ALBUM';
export const NORMALIZE_ALBUM_PHOTO = 'NORMALIZE_ALBUM_PHOTO';
export const CREATE_NEW_ALBUM = 'CREATE_NEW_ALBUM';
export const SET_SIZE_PHOTO = 'SET_SIZE_PHOTO';
export const SET_INIT = 'SET_INIT';